// Public/Core/RadiantGameplayTags.h

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

/**
 * Native GameplayTag declarations for RadiantRPG
 * These tags are automatically registered when the module loads
 */

// === NPC TYPE TAGS ===
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type);

// Humanoid NPCs
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Humanoid);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Humanoid_Villager);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Humanoid_Guard);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Humanoid_Merchant);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Humanoid_Bandit);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Humanoid_Noble);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Humanoid_Soldier);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Humanoid_Civilian);

// Creature NPCs
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Creature);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Creature_Animal);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Creature_Monster);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Creature_Undead);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Creature_Construct);

// Special NPCs
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Special);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Special_QuestGiver);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Special_Boss);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_NPC_Type_Special_Companion);

// === FACTION TAGS ===
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction);

// Major Factions
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Kingdom);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Kingdom_Guards);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Kingdom_Military);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Kingdom_Nobility);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Merchants);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Merchants_TradeGuild);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Merchants_Independent);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Bandits);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Bandits_RedCloaks);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Bandits_IronWolves);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Villagers);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Villagers_Peaceful);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Villagers_Militia);

// Special Factions
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Neutral);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Wildlife);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Hostile);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Faction_Player);

// === AI INTENT TAGS ===
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent);

// Basic Intents
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Idle);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Wander);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Patrol);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Guard);

// Survival Intents
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Survival);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Survival_Eat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Survival_Sleep);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Survival_Flee);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Survival_Hide);

// Social Intents
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Social);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Social_Talk);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Social_Trade);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Social_Follow);

// Combat Intents
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Combat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Combat_Attack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Combat_Defend);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Combat_Retreat);

// Curiosity Intents
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Curiosity);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Curiosity_Explore);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Curiosity_Investigate);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Intent_Curiosity_Watch);

// === BEHAVIOR TAGS ===
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Behavior);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Behavior_Idle);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Behavior_Moving);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Behavior_Working);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Behavior_Socializing);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Behavior_Combat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Behavior_Fleeing);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Behavior_Investigating);

// === ZONE TAGS ===
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Settlement);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Settlement_Village);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Settlement_Town);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Settlement_City);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Wilderness);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Wilderness_Forest);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Wilderness_Plains);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Wilderness_Mountains);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Dangerous);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Dangerous_BanditCamp);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Zone_Dangerous_MonsterLair);

// === AI EVENT TAGS ===
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Event);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Event_Combat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Event_Death);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Event_Social);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Event_Trade);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Event_Time);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Event_Threat);

// === SPECIES TAGS ===
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species);

// Humanoid Races
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Human);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Dwarf);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Elf);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_HalfOrc);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Goblin);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Orc);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Troll);

// Fantasy Creatures
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Dragon);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_YoungDragon);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_AncientDragon);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Vampire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Lich);

// Undead
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Zombie);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Skeleton);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Spirit);

// Animals
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Wolf);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Bear);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Deer);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Spider);

// Constructs
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Golem);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Gargoyle);

// Elementals
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Elemental);

// Aberrations
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Gazer);

// Demons & Celestials
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Demon);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Angel);

// Special Creatures
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Mimic);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Slime);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_FishMan);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_PlantMonster);

// Human Profession Variants
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Human_Scholar);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Human_Warrior);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Species_Human_Mage);

// === MEMORY TAGS ===
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory);

// Combat & Conflict Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Combat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Threat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Victory);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Defeat);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Tactics);

// Social & Emotional Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Social);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Emotion);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Trust);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Honor);

// Knowledge & Learning Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Academic);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Magic);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Craft);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Knowledge);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Research);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Technology);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Arcane);

// Survival & Nature Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Survival);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Food);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Territory);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Hunt);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Nature);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Weather);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Danger);

// Cultural & Historical Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Ancient);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Clan);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Tribe);

// Material & Possessions Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Treasure);

// Supernatural & Divine Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Divine);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Corruption);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Pure);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Aberrant);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Psychic);

// Behavioral Patterns Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Command);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Task);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Guardian);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Deception);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Adaptation);

// Environmental Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Water);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Fire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Element);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Season);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Growth);

// Social Groups Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Pack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Herd);

// Abstract Concepts Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Dominance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Justice);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Temptation);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Obsession);

// Biological & Physical Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Physical);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Blood);

// Special Categories Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Trivial);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Mundane);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Normal);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Cosmic);

// Predator/Web Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Web);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Prey);

// Environmental Hazards Memory
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Sunlight);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Memory_Desert);